application:
  host: 127.0.0.1
  port: 8000

database:
  host: 127.0.0.1
  port: 5432
  username: newsletter
  password: welcome
  database: newsletter

email_client:
  base_url: 127.0.0.1
  sender_email: peppydays@gmail.com
  authorization_token: secret
  timeout_in_milliseconds: 10000
