version: "3"

services:
  newsletter-local-db:
    image: postgres:16
    hostname: newsletter-local-db
    container_name: newsletter-local-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: newsletter
      POSTGRES_PASSWORD: welcome
      POSTGRES_DB: newsletter
    command: postgres -c "max_connections=1000"
